apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - image: kubernetes-demo:0.0.1-SNAPSHOT
          name: kubernetes-demo
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo
spec:
  selector:
    app: kubernetes-demo
  type: ClusterIP
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-demo
data:
  application-kubernetes.properties: |-
    hello.greeting="Hello (from Kubernetes ConfigMap)"